### ISSUE TITLE
Multiple motion sensors bug

### ISSUE THREAD

**Issue by BrnLng** [wallysalami/tkgpio#15]
Hi! Needed to add multiple motions sensors and the code had a bug where only the last added sensor would work at the tkinter window. Just needed to add a param to the root.bind call for class TkMotionSensor(TkDevice) at tkgpio.py:

root.bind('<Motion>', self._motion_detected**, add='+'**)

**Comment by wallysalami** [comment]
Sorry for keep you waiting! You are absolutely right. I'm going to fix it right now.
