### ISSUE TITLE
Unable to run the simple_circuit.py example

### ISSUE THREAD

**Issue by jiortigosa** [wallysalami/tkgpio#3]
Hello,
I'm quite a novice in the gpio usage.
I want to emulate a Raspberry Pi with gpio to play with it.
I am using a vmware virtual machine with Raspbian OS Desktop.
When I try to run the simple_circui.py, I get an error at the very first line, when trying to import the TKCircuit from tkgpio.

It has something to do with something called PortAudio  library
======================
File "/xxxx/emulador01.py", line 3, in <module>
    from tkgpio import TkCircuit
File "/home/pi/.local/lib/python3.7/site-packages/tkgpio/__init__.py", line 1, in <module>
    from .tkgpio import *
File "/home/pi/.local/lib/python3.7/site-packages/tkgpio/tkgpio.py", line 6, in <module>
    from sounddevice import play, stop
File "/home/pi/.local/lib/python3.7/site-packages/sounddevice.py", line 71, in <module>
    raise OSError('PortAudio library not found')
OSError: PortAudio library not found

==========================

I would appreciatte some help...

[emulador01.pdf](https://github.com/wallysalami/tkgpio/files/6097493/emulador01.pdf)

**Comment by wallysalami** [comment]
Hello, there!

Running tkgpio on Linux requires the `portaudio19-dev` library, which can be installed with your package manager (i.e. apt-get).

I will explain that next time I update the README. Maybe there is way to put it as a dependency on setup.py. Or I could disable the buzzer sound if PortAudio is not available.

**Comment by jiortigosa** [comment]
It did fix it!
Thank you!
