### ISSUE TITLE
Feature Request: Add text labels

### ISSUE THREAD

**Issue by alan-rpi** [wallysalami/tkgpio#5]
Many thanks for making this excellent simulator available. It's been a real help for developing a Rasp Pi app. 

One feature that would be useful is plain text labels to the interface. At the moment I had to use a buzzer but that means I have 2 less gpios and it looks ugly! 

![EMS](https://user-images.githubusercontent.com/25422008/120831315-51cabd80-c557-11eb-8807-0b46569be7ad.jpg)
Purchase and Sell just need to be labels

**Comment by wallysalami** [comment]
Hello, there! Thanks! Always a pleasure to hear that my humble library is being useful around the world. 😊

Indeed, labels would be a simple and useful addition to tkgpio. I'll start working on that.

By the way, your application there looks interesting. What does it do exactly?

**Comment by alan-rpi** [comment]
It's an energy management system (EMS). There are 3 x inputs from 3 x electricity meters: PV generation, Consumption and Purchase. There is 1 pulse for each kW of energy. The system switches on an electric hot water system if there is surplus energy. If at the end of the day the hot water was not on for sufficient time then it will be switched on anyway. Lots of user configuration settings done through the screen and the push buttons The bottom half of the simulator screen is set the pulse rates and to force certain test conditions.  The top half will be the user control panel.

Meter are connected to a Pico that sends the counts to a Pi. That is where the EMS app is. It then send commands to the electric hot water system using zigbee via zigbee2MQTT and mosquitto. I plan to add statistics using Grafana and InfluxDB. At the moment I am soldering the components. I hope it all works!

It would be great to have labels. It will save me 2 x gpios!

Alan

**Comment by wallysalami** [comment]
There you go: 95945d0 adds support for labels. You can use them to insert texts and even rectangles. Check [this file](https://github.com/wallysalami/tkgpio/blob/76588f7/docs/examples/analog_control/setup.py#L32) for usage.

> It's an energy management system (EMS). There are 3 x inputs from 3 x electricity meters: PV generation, Consumption and Purchase. There is 1 pulse for each kW of energy. The system switches on an electric hot water system if there is surplus energy.

Cool! I've never used Raspberry Pi for high voltage equipment.

> It then send commands to the electric hot water system using [zigbee](https://en.wikipedia.org/wiki/Zigbee) via [zigbee2MQTT](https://github.com/koenkk/zigbee2mqtt) and [mosquitto](https://mosquitto.org). I plan to add statistics using [Grafana](https://en.wikipedia.org/wiki/Grafana) and [InfluxDB](https://en.wikipedia.org/wiki/InfluxDB).

As Captain Barbossa once said, "There are a lot of long words in there". I googled them and added the links for the lazy ones. Looks fancy though! Good luck in your endeavours and thank you for the label suggestion.
